// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlknqvKzrGQGhYho8I4j_4ejKYNrH3hbs',
    appId: '1:924996299433:web:a9f95137fddc84efffd7b8',
    messagingSenderId: '924996299433',
    projectId: 'messageapp-d40ad',
    authDomain: 'messageapp-d40ad.firebaseapp.com',
    storageBucket: 'messageapp-d40ad.appspot.com',
    measurementId: 'G-YP4KVDHQP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSyu_0HZaj2IcjckRItH-Gl1aLpOkOq88',
    appId: '1:924996299433:android:cfe12595433ff059ffd7b8',
    messagingSenderId: '924996299433',
    projectId: 'messageapp-d40ad',
    storageBucket: 'messageapp-d40ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEfe2JeIDFPIwxMYPcUKCyFAeSKjDEAbc',
    appId: '1:924996299433:ios:f99865883859c04effd7b8',
    messagingSenderId: '924996299433',
    projectId: 'messageapp-d40ad',
    storageBucket: 'messageapp-d40ad.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEfe2JeIDFPIwxMYPcUKCyFAeSKjDEAbc',
    appId: '1:924996299433:ios:f99865883859c04effd7b8',
    messagingSenderId: '924996299433',
    projectId: 'messageapp-d40ad',
    storageBucket: 'messageapp-d40ad.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlknqvKzrGQGhYho8I4j_4ejKYNrH3hbs',
    appId: '1:924996299433:web:fad03363b93d97beffd7b8',
    messagingSenderId: '924996299433',
    projectId: 'messageapp-d40ad',
    authDomain: 'messageapp-d40ad.firebaseapp.com',
    storageBucket: 'messageapp-d40ad.appspot.com',
    measurementId: 'G-06P5EJQ5X6',
  );

}